eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true